language: php

php:
- '8.1'

os: linux

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE book_shop'
  - mysql book_shop > default.sql

before script:
  - composer update
  - composer install --no-interaction
  - cp .env.example .env
  - php artisan key:generate

script:
  - php artisan test